nyc_taxi_pipeline:
  outputs:
    dev:
      dataset: staging
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: 'nyc-taxi-dbt-devia'
      threads: 4
      type: bigquery
  target: dev
